# Importing BaseModel from Pydantic
# BaseModel -> Core class in Pydantic used to define data schemas
# It provides validation, serialization and parsing of data
from pydantic import BaseModel

# Importing datetime class
# datetime -> Used to handle date and time values (e.g., appointment time)
from datetime import datetime

# Schema for creating a new appointment (used in request body)
class AppointmentCreate(BaseModel):
    
    # doctor_id -> ID of the doctor for the appointment
    # int -> Data Type (must be an integer)
    # This will be provided by the user when creating an appointment
    doctor_id: int
    
    # date_time -> Date and time of the appointment
    # datetime -> Ensures valid date-time format (auto-generated by Pydantic)
    date_time: datetime
    

# Schema for sending appointment data as a response (API Response)    
class AppointmentResponse(BaseModel):
    
    # id -> Unique identifier of the appointment (Primary key from DB)
    id: int
    
    # patient_id -> ID of the patient who booked the appointment
    patient_id: int
    
    # date_time -> Id of the assigned doctor
    doctor_id: int
    
    # date_time -> Appointment date and time
    date_time: datetime
    
    # status -> Current state of appointment (e.g., "Booked", "Completed", "cancelled")
    status: str
    
    # Config -> Special class used to configure Pydantic behavior
    # orm_mode = True ->
    # - Allows Pydantic to read data directly from ORM objects (like SQLAlchemy models)
    # - Without this, it excepts dictionaries only
    # - With this, return DB objects directly in FastAPI responses
    class Config:
        orm_mode = True
    